name: Java CI

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Dependencies
        run: ./gradlew build
      
      - name: Run Linter
        run: ./gradlew lint

      - name: Run Tests & Publish Code Coverage
        run: ./gradlew test
